package io.lightine.tessera.mrz.recognition

import io.lightine.tessera.types.vocabulary.CountryCodeCategory

/**
 * The SDK's recognized country codes for MRZ issuing state and nationality positions.
 *
 * Contains:
 * - All currently-assigned ISO 3166-1 alpha-3 country codes (categorized as [`STATE`][CountryCodeCategory.STATE])
 * - ICAO Doc 9303 Part 3 §5 extensions (Parts A through H): special nationality codes
 *   for British classes, the European Union, United Nations documents, international
 *   organizations, stateless persons, refugees, deprecated states, the synthetic specimen
 *   code, and ICAO's own master-list-signing code
 *
 * **Verification context.** Populated during the 2026-05-18 pre-tag conformance pass
 * (finding F7) — see `CONFORMANCE-NOTES-2026-05-18.md`. The ISO 3166-1 alpha-3 codes
 * are widely-treated facts; community-maintained datasets (e.g., the Debian `iso-codes`
 * package) embed identical content. The ICAO §5 extensions are read from Doc 9303 Part 3.
 *
 * Codes not present in this table surface as
 * [`MrzUnknownCountryCode`][io.lightine.tessera.types.errors.MrzUnknownCountryCode]
 * warnings rather than validation failures, per
 * [ADR-013](https://lightine.youtrack.cloud/articles/TES-A-44).
 *
 * **Note on countries in transition.** ISO 3166-1 occasionally updates entries (name
 * changes, code additions, code reservations). This table reflects the assignments as of
 * the 2026-05-18 verification; deprecated codes that ICAO §5 specifically references for
 * backward compatibility on still-circulating documents (Netherlands Antilles `ANT`,
 * Neutral Zone `NTZ`) are categorized as [`HISTORICAL`][CountryCodeCategory.HISTORICAL].
 */
public object CountryCodeTable {
    private val entries: List<CountryCodeEntry> =
        listOf(
            // ===========================================================================
            // ISO 3166-1 alpha-3 — officially assigned codes (category STATE)
            // Sourced from the ISO 3166 Maintenance Agency listing; English short names.
            // ===========================================================================
            CountryCodeEntry("ABW", "Aruba", CountryCodeCategory.STATE),
            CountryCodeEntry("AFG", "Afghanistan", CountryCodeCategory.STATE),
            CountryCodeEntry("AGO", "Angola", CountryCodeCategory.STATE),
            CountryCodeEntry("AIA", "Anguilla", CountryCodeCategory.STATE),
            CountryCodeEntry("ALA", "Åland Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("ALB", "Albania", CountryCodeCategory.STATE),
            CountryCodeEntry("AND", "Andorra", CountryCodeCategory.STATE),
            CountryCodeEntry("ARE", "United Arab Emirates", CountryCodeCategory.STATE),
            CountryCodeEntry("ARG", "Argentina", CountryCodeCategory.STATE),
            CountryCodeEntry("ARM", "Armenia", CountryCodeCategory.STATE),
            CountryCodeEntry("ASM", "American Samoa", CountryCodeCategory.STATE),
            CountryCodeEntry("ATA", "Antarctica", CountryCodeCategory.STATE),
            CountryCodeEntry("ATF", "French Southern and Antarctic Lands", CountryCodeCategory.STATE),
            CountryCodeEntry("ATG", "Antigua and Barbuda", CountryCodeCategory.STATE),
            CountryCodeEntry("AUS", "Australia", CountryCodeCategory.STATE),
            CountryCodeEntry("AUT", "Austria", CountryCodeCategory.STATE),
            CountryCodeEntry("AZE", "Azerbaijan", CountryCodeCategory.STATE),
            CountryCodeEntry("BDI", "Burundi", CountryCodeCategory.STATE),
            CountryCodeEntry("BEL", "Belgium", CountryCodeCategory.STATE),
            CountryCodeEntry("BEN", "Benin", CountryCodeCategory.STATE),
            CountryCodeEntry("BES", "Caribbean Netherlands", CountryCodeCategory.STATE),
            CountryCodeEntry("BFA", "Burkina Faso", CountryCodeCategory.STATE),
            CountryCodeEntry("BGD", "Bangladesh", CountryCodeCategory.STATE),
            CountryCodeEntry("BGR", "Bulgaria", CountryCodeCategory.STATE),
            CountryCodeEntry("BHR", "Bahrain", CountryCodeCategory.STATE),
            CountryCodeEntry("BHS", "The Bahamas", CountryCodeCategory.STATE),
            CountryCodeEntry("BIH", "Bosnia and Herzegovina", CountryCodeCategory.STATE),
            CountryCodeEntry("BLM", "Saint Barthélemy", CountryCodeCategory.STATE),
            CountryCodeEntry("BLR", "Belarus", CountryCodeCategory.STATE),
            CountryCodeEntry("BLZ", "Belize", CountryCodeCategory.STATE),
            CountryCodeEntry("BMU", "Bermuda", CountryCodeCategory.STATE),
            CountryCodeEntry("BOL", "Bolivia", CountryCodeCategory.STATE),
            CountryCodeEntry("BRA", "Brazil", CountryCodeCategory.STATE),
            CountryCodeEntry("BRB", "Barbados", CountryCodeCategory.STATE),
            CountryCodeEntry("BRN", "Brunei", CountryCodeCategory.STATE),
            CountryCodeEntry("BTN", "Bhutan", CountryCodeCategory.STATE),
            CountryCodeEntry("BVT", "Bouvet Island", CountryCodeCategory.STATE),
            CountryCodeEntry("BWA", "Botswana", CountryCodeCategory.STATE),
            CountryCodeEntry("CAF", "Central African Republic", CountryCodeCategory.STATE),
            CountryCodeEntry("CAN", "Canada", CountryCodeCategory.STATE),
            CountryCodeEntry("CCK", "Cocos (Keeling) Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("CHE", "Switzerland", CountryCodeCategory.STATE),
            CountryCodeEntry("CHL", "Chile", CountryCodeCategory.STATE),
            CountryCodeEntry("CHN", "China", CountryCodeCategory.STATE),
            CountryCodeEntry("CIV", "Côte d'Ivoire", CountryCodeCategory.STATE),
            CountryCodeEntry("CMR", "Cameroon", CountryCodeCategory.STATE),
            CountryCodeEntry("COD", "Democratic Republic of the Congo", CountryCodeCategory.STATE),
            CountryCodeEntry("COG", "Republic of the Congo", CountryCodeCategory.STATE),
            CountryCodeEntry("COK", "Cook Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("COL", "Colombia", CountryCodeCategory.STATE),
            CountryCodeEntry("COM", "Comoros", CountryCodeCategory.STATE),
            CountryCodeEntry("CPV", "Cabo Verde", CountryCodeCategory.STATE),
            CountryCodeEntry("CRI", "Costa Rica", CountryCodeCategory.STATE),
            CountryCodeEntry("CUB", "Cuba", CountryCodeCategory.STATE),
            CountryCodeEntry("CUW", "Curaçao", CountryCodeCategory.STATE),
            CountryCodeEntry("CXR", "Christmas Island", CountryCodeCategory.STATE),
            CountryCodeEntry("CYM", "Cayman Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("CYP", "Cyprus", CountryCodeCategory.STATE),
            CountryCodeEntry("CZE", "Czechia", CountryCodeCategory.STATE),
            CountryCodeEntry("DEU", "Germany", CountryCodeCategory.STATE),
            CountryCodeEntry("DJI", "Djibouti", CountryCodeCategory.STATE),
            CountryCodeEntry("DMA", "Dominica", CountryCodeCategory.STATE),
            CountryCodeEntry("DNK", "Denmark", CountryCodeCategory.STATE),
            CountryCodeEntry("DOM", "Dominican Republic", CountryCodeCategory.STATE),
            CountryCodeEntry("DZA", "Algeria", CountryCodeCategory.STATE),
            CountryCodeEntry("ECU", "Ecuador", CountryCodeCategory.STATE),
            CountryCodeEntry("EGY", "Egypt", CountryCodeCategory.STATE),
            CountryCodeEntry("ERI", "Eritrea", CountryCodeCategory.STATE),
            CountryCodeEntry("ESH", "Western Sahara", CountryCodeCategory.STATE),
            CountryCodeEntry("ESP", "Spain", CountryCodeCategory.STATE),
            CountryCodeEntry("EST", "Estonia", CountryCodeCategory.STATE),
            CountryCodeEntry("ETH", "Ethiopia", CountryCodeCategory.STATE),
            CountryCodeEntry("FIN", "Finland", CountryCodeCategory.STATE),
            CountryCodeEntry("FJI", "Fiji", CountryCodeCategory.STATE),
            CountryCodeEntry("FLK", "Falkland Islands (Malvinas)", CountryCodeCategory.STATE),
            CountryCodeEntry("FRA", "France", CountryCodeCategory.STATE),
            CountryCodeEntry("FRO", "Faroe Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("FSM", "Micronesia, Federated States of", CountryCodeCategory.STATE),
            CountryCodeEntry("GAB", "Gabon", CountryCodeCategory.STATE),
            CountryCodeEntry("GBR", "United Kingdom of Great Britain and Northern Ireland", CountryCodeCategory.STATE),
            CountryCodeEntry("GEO", "Georgia", CountryCodeCategory.STATE),
            CountryCodeEntry("GGY", "Guernsey", CountryCodeCategory.STATE),
            CountryCodeEntry("GHA", "Ghana", CountryCodeCategory.STATE),
            CountryCodeEntry("GIB", "Gibraltar", CountryCodeCategory.STATE),
            CountryCodeEntry("GIN", "Guinea", CountryCodeCategory.STATE),
            CountryCodeEntry("GLP", "Guadeloupe", CountryCodeCategory.STATE),
            CountryCodeEntry("GMB", "Gambia", CountryCodeCategory.STATE),
            CountryCodeEntry("GNB", "Guinea-Bissau", CountryCodeCategory.STATE),
            CountryCodeEntry("GNQ", "Equatorial Guinea", CountryCodeCategory.STATE),
            CountryCodeEntry("GRC", "Greece", CountryCodeCategory.STATE),
            CountryCodeEntry("GRD", "Grenada", CountryCodeCategory.STATE),
            CountryCodeEntry("GRL", "Greenland", CountryCodeCategory.STATE),
            CountryCodeEntry("GTM", "Guatemala", CountryCodeCategory.STATE),
            CountryCodeEntry("GUF", "French Guiana", CountryCodeCategory.STATE),
            CountryCodeEntry("GUM", "Guam", CountryCodeCategory.STATE),
            CountryCodeEntry("GUY", "Guyana", CountryCodeCategory.STATE),
            CountryCodeEntry("HKG", "Hong Kong", CountryCodeCategory.STATE),
            CountryCodeEntry("HMD", "Heard Island and McDonald Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("HND", "Honduras", CountryCodeCategory.STATE),
            CountryCodeEntry("HRV", "Croatia", CountryCodeCategory.STATE),
            CountryCodeEntry("HTI", "Haiti", CountryCodeCategory.STATE),
            CountryCodeEntry("HUN", "Hungary", CountryCodeCategory.STATE),
            CountryCodeEntry("IDN", "Indonesia", CountryCodeCategory.STATE),
            CountryCodeEntry("IMN", "Isle of Man", CountryCodeCategory.STATE),
            CountryCodeEntry("IND", "India", CountryCodeCategory.STATE),
            CountryCodeEntry("IOT", "British Indian Ocean Territory", CountryCodeCategory.STATE),
            CountryCodeEntry("IRL", "Ireland", CountryCodeCategory.STATE),
            CountryCodeEntry("IRN", "Iran, Islamic Republic of", CountryCodeCategory.STATE),
            CountryCodeEntry("IRQ", "Iraq", CountryCodeCategory.STATE),
            CountryCodeEntry("ISL", "Iceland", CountryCodeCategory.STATE),
            CountryCodeEntry("ISR", "Israel", CountryCodeCategory.STATE),
            CountryCodeEntry("ITA", "Italy", CountryCodeCategory.STATE),
            CountryCodeEntry("JAM", "Jamaica", CountryCodeCategory.STATE),
            CountryCodeEntry("JEY", "Jersey", CountryCodeCategory.STATE),
            CountryCodeEntry("JOR", "Jordan", CountryCodeCategory.STATE),
            CountryCodeEntry("JPN", "Japan", CountryCodeCategory.STATE),
            CountryCodeEntry("KAZ", "Kazakhstan", CountryCodeCategory.STATE),
            CountryCodeEntry("KEN", "Kenya", CountryCodeCategory.STATE),
            CountryCodeEntry("KGZ", "Kyrgyzstan", CountryCodeCategory.STATE),
            CountryCodeEntry("KHM", "Cambodia", CountryCodeCategory.STATE),
            CountryCodeEntry("KIR", "Kiribati", CountryCodeCategory.STATE),
            CountryCodeEntry("KNA", "Saint Kitts and Nevis", CountryCodeCategory.STATE),
            CountryCodeEntry("KOR", "Korea, Republic of", CountryCodeCategory.STATE),
            CountryCodeEntry("KWT", "Kuwait", CountryCodeCategory.STATE),
            CountryCodeEntry("LAO", "Lao People's Democratic Republic", CountryCodeCategory.STATE),
            CountryCodeEntry("LBN", "Lebanon", CountryCodeCategory.STATE),
            CountryCodeEntry("LBR", "Liberia", CountryCodeCategory.STATE),
            CountryCodeEntry("LBY", "Libya", CountryCodeCategory.STATE),
            CountryCodeEntry("LCA", "Saint Lucia", CountryCodeCategory.STATE),
            CountryCodeEntry("LIE", "Liechtenstein", CountryCodeCategory.STATE),
            CountryCodeEntry("LKA", "Sri Lanka", CountryCodeCategory.STATE),
            CountryCodeEntry("LSO", "Lesotho", CountryCodeCategory.STATE),
            CountryCodeEntry("LTU", "Lithuania", CountryCodeCategory.STATE),
            CountryCodeEntry("LUX", "Luxembourg", CountryCodeCategory.STATE),
            CountryCodeEntry("LVA", "Latvia", CountryCodeCategory.STATE),
            CountryCodeEntry("MAC", "Macao", CountryCodeCategory.STATE),
            CountryCodeEntry("MAF", "Saint Martin (French part)", CountryCodeCategory.STATE),
            CountryCodeEntry("MAR", "Morocco", CountryCodeCategory.STATE),
            CountryCodeEntry("MCO", "Monaco", CountryCodeCategory.STATE),
            CountryCodeEntry("MDA", "Moldova, Republic of", CountryCodeCategory.STATE),
            CountryCodeEntry("MDG", "Madagascar", CountryCodeCategory.STATE),
            CountryCodeEntry("MDV", "Maldives", CountryCodeCategory.STATE),
            CountryCodeEntry("MEX", "Mexico", CountryCodeCategory.STATE),
            CountryCodeEntry("MHL", "Marshall Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("MKD", "North Macedonia", CountryCodeCategory.STATE),
            CountryCodeEntry("MLI", "Mali", CountryCodeCategory.STATE),
            CountryCodeEntry("MLT", "Malta", CountryCodeCategory.STATE),
            CountryCodeEntry("MMR", "Myanmar", CountryCodeCategory.STATE),
            CountryCodeEntry("MNE", "Montenegro", CountryCodeCategory.STATE),
            CountryCodeEntry("MNG", "Mongolia", CountryCodeCategory.STATE),
            CountryCodeEntry("MNP", "Northern Mariana Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("MOZ", "Mozambique", CountryCodeCategory.STATE),
            CountryCodeEntry("MRT", "Mauritania", CountryCodeCategory.STATE),
            CountryCodeEntry("MSR", "Montserrat", CountryCodeCategory.STATE),
            CountryCodeEntry("MTQ", "Martinique", CountryCodeCategory.STATE),
            CountryCodeEntry("MUS", "Mauritius", CountryCodeCategory.STATE),
            CountryCodeEntry("MWI", "Malawi", CountryCodeCategory.STATE),
            CountryCodeEntry("MYS", "Malaysia", CountryCodeCategory.STATE),
            CountryCodeEntry("MYT", "Mayotte", CountryCodeCategory.STATE),
            CountryCodeEntry("NAM", "Namibia", CountryCodeCategory.STATE),
            CountryCodeEntry("NCL", "New Caledonia", CountryCodeCategory.STATE),
            CountryCodeEntry("NER", "Niger", CountryCodeCategory.STATE),
            CountryCodeEntry("NFK", "Norfolk Island", CountryCodeCategory.STATE),
            CountryCodeEntry("NGA", "Nigeria", CountryCodeCategory.STATE),
            CountryCodeEntry("NIC", "Nicaragua", CountryCodeCategory.STATE),
            CountryCodeEntry("NIU", "Niue", CountryCodeCategory.STATE),
            CountryCodeEntry("NLD", "Netherlands, Kingdom of the", CountryCodeCategory.STATE),
            CountryCodeEntry("NOR", "Norway", CountryCodeCategory.STATE),
            CountryCodeEntry("NPL", "Nepal", CountryCodeCategory.STATE),
            CountryCodeEntry("NRU", "Nauru", CountryCodeCategory.STATE),
            CountryCodeEntry("NZL", "New Zealand", CountryCodeCategory.STATE),
            CountryCodeEntry("OMN", "Oman", CountryCodeCategory.STATE),
            CountryCodeEntry("PAK", "Pakistan", CountryCodeCategory.STATE),
            CountryCodeEntry("PAN", "Panama", CountryCodeCategory.STATE),
            CountryCodeEntry("PCN", "Pitcairn", CountryCodeCategory.STATE),
            CountryCodeEntry("PER", "Peru", CountryCodeCategory.STATE),
            CountryCodeEntry("PHL", "Philippines", CountryCodeCategory.STATE),
            CountryCodeEntry("PLW", "Palau", CountryCodeCategory.STATE),
            CountryCodeEntry("PNG", "Papua New Guinea", CountryCodeCategory.STATE),
            CountryCodeEntry("POL", "Poland", CountryCodeCategory.STATE),
            CountryCodeEntry("PRI", "Puerto Rico", CountryCodeCategory.STATE),
            CountryCodeEntry("PRK", "Korea, Democratic People's Republic of", CountryCodeCategory.STATE),
            CountryCodeEntry("PRT", "Portugal", CountryCodeCategory.STATE),
            CountryCodeEntry("PRY", "Paraguay", CountryCodeCategory.STATE),
            CountryCodeEntry("PSE", "Palestine, State of", CountryCodeCategory.STATE),
            CountryCodeEntry("PYF", "French Polynesia", CountryCodeCategory.STATE),
            CountryCodeEntry("QAT", "Qatar", CountryCodeCategory.STATE),
            CountryCodeEntry("REU", "Réunion", CountryCodeCategory.STATE),
            CountryCodeEntry("ROU", "Romania", CountryCodeCategory.STATE),
            CountryCodeEntry("RUS", "Russian Federation", CountryCodeCategory.STATE),
            CountryCodeEntry("RWA", "Rwanda", CountryCodeCategory.STATE),
            CountryCodeEntry("SAU", "Saudi Arabia", CountryCodeCategory.STATE),
            CountryCodeEntry("SDN", "Sudan", CountryCodeCategory.STATE),
            CountryCodeEntry("SEN", "Senegal", CountryCodeCategory.STATE),
            CountryCodeEntry("SGP", "Singapore", CountryCodeCategory.STATE),
            CountryCodeEntry("SGS", "South Georgia and the South Sandwich Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("SHN", "Saint Helena, Ascension and Tristan da Cunha", CountryCodeCategory.STATE),
            CountryCodeEntry("SJM", "Svalbard and Jan Mayen", CountryCodeCategory.STATE),
            CountryCodeEntry("SLB", "Solomon Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("SLE", "Sierra Leone", CountryCodeCategory.STATE),
            CountryCodeEntry("SLV", "El Salvador", CountryCodeCategory.STATE),
            CountryCodeEntry("SMR", "San Marino", CountryCodeCategory.STATE),
            CountryCodeEntry("SOM", "Somalia", CountryCodeCategory.STATE),
            CountryCodeEntry("SPM", "Saint Pierre and Miquelon", CountryCodeCategory.STATE),
            CountryCodeEntry("SRB", "Serbia", CountryCodeCategory.STATE),
            CountryCodeEntry("SSD", "South Sudan", CountryCodeCategory.STATE),
            CountryCodeEntry("STP", "Sao Tome and Principe", CountryCodeCategory.STATE),
            CountryCodeEntry("SUR", "Suriname", CountryCodeCategory.STATE),
            CountryCodeEntry("SVK", "Slovakia", CountryCodeCategory.STATE),
            CountryCodeEntry("SVN", "Slovenia", CountryCodeCategory.STATE),
            CountryCodeEntry("SWE", "Sweden", CountryCodeCategory.STATE),
            CountryCodeEntry("SWZ", "Eswatini", CountryCodeCategory.STATE),
            CountryCodeEntry("SXM", "Sint Maarten (Dutch part)", CountryCodeCategory.STATE),
            CountryCodeEntry("SYC", "Seychelles", CountryCodeCategory.STATE),
            CountryCodeEntry("SYR", "Syrian Arab Republic", CountryCodeCategory.STATE),
            CountryCodeEntry("TCA", "Turks and Caicos Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("TCD", "Chad", CountryCodeCategory.STATE),
            CountryCodeEntry("TGO", "Togo", CountryCodeCategory.STATE),
            CountryCodeEntry("THA", "Thailand", CountryCodeCategory.STATE),
            CountryCodeEntry("TJK", "Tajikistan", CountryCodeCategory.STATE),
            CountryCodeEntry("TKL", "Tokelau", CountryCodeCategory.STATE),
            CountryCodeEntry("TKM", "Turkmenistan", CountryCodeCategory.STATE),
            CountryCodeEntry("TLS", "Timor-Leste", CountryCodeCategory.STATE),
            CountryCodeEntry("TON", "Tonga", CountryCodeCategory.STATE),
            CountryCodeEntry("TTO", "Trinidad and Tobago", CountryCodeCategory.STATE),
            CountryCodeEntry("TUN", "Tunisia", CountryCodeCategory.STATE),
            CountryCodeEntry("TUR", "Türkiye", CountryCodeCategory.STATE),
            CountryCodeEntry("TUV", "Tuvalu", CountryCodeCategory.STATE),
            CountryCodeEntry("TWN", "Taiwan, Province of China", CountryCodeCategory.STATE),
            CountryCodeEntry("TZA", "Tanzania, United Republic of", CountryCodeCategory.STATE),
            CountryCodeEntry("UGA", "Uganda", CountryCodeCategory.STATE),
            CountryCodeEntry("UKR", "Ukraine", CountryCodeCategory.STATE),
            CountryCodeEntry("UMI", "United States Minor Outlying Islands", CountryCodeCategory.STATE),
            CountryCodeEntry("URY", "Uruguay", CountryCodeCategory.STATE),
            CountryCodeEntry("USA", "United States of America", CountryCodeCategory.STATE),
            CountryCodeEntry("UZB", "Uzbekistan", CountryCodeCategory.STATE),
            CountryCodeEntry("VAT", "Holy See", CountryCodeCategory.STATE),
            CountryCodeEntry("VCT", "Saint Vincent and the Grenadines", CountryCodeCategory.STATE),
            CountryCodeEntry("VEN", "Venezuela, Bolivarian Republic of", CountryCodeCategory.STATE),
            CountryCodeEntry("VGB", "Virgin Islands (British)", CountryCodeCategory.STATE),
            CountryCodeEntry("VIR", "Virgin Islands (U.S.)", CountryCodeCategory.STATE),
            CountryCodeEntry("VNM", "Viet Nam", CountryCodeCategory.STATE),
            CountryCodeEntry("VUT", "Vanuatu", CountryCodeCategory.STATE),
            CountryCodeEntry("WLF", "Wallis and Futuna", CountryCodeCategory.STATE),
            CountryCodeEntry("WSM", "Samoa", CountryCodeCategory.STATE),
            CountryCodeEntry("YEM", "Yemen", CountryCodeCategory.STATE),
            CountryCodeEntry("ZAF", "South Africa", CountryCodeCategory.STATE),
            CountryCodeEntry("ZMB", "Zambia", CountryCodeCategory.STATE),
            CountryCodeEntry("ZWE", "Zimbabwe", CountryCodeCategory.STATE),
            // ===========================================================================
            // ICAO Doc 9303 Part 3 §5 — Extensions to ISO 3166-1
            // ===========================================================================
            // Part A — British nationality classes + Kosovo (operational use)
            CountryCodeEntry("GBD", "British Overseas Territories Citizen", CountryCodeCategory.STATE),
            CountryCodeEntry("GBN", "British National (Overseas)", CountryCodeCategory.STATE),
            CountryCodeEntry("GBO", "British Overseas Citizen", CountryCodeCategory.STATE),
            CountryCodeEntry("GBP", "British Protected Person", CountryCodeCategory.STATE),
            CountryCodeEntry("GBS", "British Subject", CountryCodeCategory.STATE),
            CountryCodeEntry("RKS", "Kosovo", CountryCodeCategory.STATE),
            // Part B — Other codes reserved by ISO 3166/MA
            CountryCodeEntry("EUE", "European Union", CountryCodeCategory.ORGANIZATION),
            // Part C — Codes for United Nations travel documents
            CountryCodeEntry("UNO", "United Nations Organization or one of its officials", CountryCodeCategory.ORGANIZATION),
            CountryCodeEntry("UNA", "United Nations specialized agency or one of its officials", CountryCodeCategory.ORGANIZATION),
            CountryCodeEntry("UNK", "Resident of Kosovo, document issued by UNMIK", CountryCodeCategory.STATE),
            // Part D — Codes for other issuing authorities
            CountryCodeEntry("XPO", "International Criminal Police Organization (INTERPOL)", CountryCodeCategory.ORGANIZATION),
            CountryCodeEntry("XES", "Organization of Eastern Caribbean States (OECS)", CountryCodeCategory.ORGANIZATION),
            CountryCodeEntry("XMP", "Parliamentary Assembly of the Mediterranean (PAM)", CountryCodeCategory.ORGANIZATION),
            CountryCodeEntry("XOM", "Sovereign Military Order of Malta or one of its emissaries", CountryCodeCategory.ORGANIZATION),
            CountryCodeEntry("XDC", "Southern African Development Community", CountryCodeCategory.ORGANIZATION),
            // Part E — Codes for persons without a defined nationality
            CountryCodeEntry("XXA", "Stateless person (per 1954 Convention)", CountryCodeCategory.STATELESS),
            CountryCodeEntry("XXB", "Refugee (per 1951 Convention and 1967 Protocol)", CountryCodeCategory.REFUGEE),
            CountryCodeEntry("XXC", "Refugee (other than under code XXB)", CountryCodeCategory.REFUGEE),
            CountryCodeEntry("XXX", "Person of unspecified nationality", CountryCodeCategory.OTHER),
            // Part F — Codes deprecated in ISO 3166 (kept for backward compatibility)
            CountryCodeEntry("ANT", "Netherlands Antilles", CountryCodeCategory.HISTORICAL),
            CountryCodeEntry("NTZ", "Neutral Zone", CountryCodeCategory.HISTORICAL),
            // Part G — Code used in specimen documents (synthetic; not a real country)
            CountryCodeEntry("UTO", "Utopia", CountryCodeCategory.OTHER),
            // Part H — Code used by ICAO when digitally signing a master list
            CountryCodeEntry("IAO", "International Civil Aviation Organization", CountryCodeCategory.ORGANIZATION),
        )

    private val byCode: Map<String, CountryCodeEntry> = entries.associateBy { it.code }

    /** Returns the entry for [code], or `null` if the code is not in the table. */
    public fun lookup(code: String): CountryCodeEntry? = byCode[code]

    /** Returns every entry currently in the table, in registration order. */
    public fun all(): List<CountryCodeEntry> = entries

    /** Returns every entry in the table whose category matches [category]. */
    public fun byCategory(category: CountryCodeCategory): List<CountryCodeEntry> = entries.filter { it.category == category }
}
